imgquik/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    
    url(r'^', include('placeholder.urls', namespace='placeholder')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

placeholder/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^image/(?P<width>\d+)/$', views.placeholder_shortcut, name='placeholder_shortcut'),
    url(r'^image/(?P<width>\d+)x(?P<height>\d+)/$', views.placeholder, name='placeholder'),
    url(r'^image/(?P<width>\d+)x(?P<height>\d+)/(?P<bg>\w+)/$', views.placeholder, name='placeholder_bg'),
    url(r'^image/(?P<width>\d+)x(?P<height>\d+)/(?P<bg>\w+)/(?P<fg>\w+)/$', views.placeholder, name='placeholder_bg_fg'),
    url(r'^$', views.index, name='homepage'),
]

placeholder/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

utils/models.py
from django.db import models

class Timestamped(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

placeholder/forms.py
from django import forms

from io import BytesIO
from PIL import Image, ImageDraw
from django.core.cache import cache

class ImageForm(forms.Form):
    """Form to validate requested placeholder image."""

    width = forms.IntegerField(min_value=1, max_value=2000)
    height = forms.IntegerField(min_value=1, max_value=2000)

    def generate(self, image_format='PNG', bg='#FFFFFF', fg='#000000'):
        """Generate an image of the given type and return as raw bytes."""
        width = self.cleaned_data['width']
        height = self.cleaned_data['height']
        key = '{}.{}.{}.{}.{}'.format(width, height, image_format, bg, fg)
        content = cache.get(key)
        if content is None:
            image = Image.new('RGB', (width, height), bg)
            draw = ImageDraw.Draw(image)
            text = '{} x {}'.format(width, height)
            textwidth, textheight = draw.textsize(text)
            if textwidth < width and textheight < height:
                texttop = (height - textheight) // 2
                textleft = (width - textwidth) // 2
                draw.text((textleft, texttop), text, fill=fg)
            content = BytesIO()
            image.save(content, image_format)
            content.seek(0)
            cache.set(key, content, 60 * 60)
        return content

placeholder/views.py
from __future__ import unicode_literals

import hashlib

from django.shortcuts import render, reverse, redirect
from django.http import HttpResponse, HttpResponseBadRequest
from django.views.decorators.http import etag

from .forms import ImageForm


def generate_etag(request, width, height, bg=None, fg=None):
    content = 'Placeholder: {0} x {1} BG: {2} FG: {3}'.format(width, height, bg, fg)
    return hashlib.sha1(content.encode('utf-8')).hexdigest()


@etag(generate_etag)
def placeholder(request, width, height, bg='FFFFFF', fg='000000'):
    form = ImageForm({'width': width, 'height': height})
    if form.is_valid():
        image = form.generate(bg='#{}'.format(bg), fg='#{}'.format(fg))
        return HttpResponse(image, content_type='image/png')
    else:
        return  HttpResponseBadRequest('Invalid Image Request')


def index(request):
    example = reverse('placeholder:placeholder', kwargs={'width': 100, 'height': 50})
    context = {
        'example': request.build_absolute_uri(example)
    }
    return render(request, 'placeholder/home.html', context)


def placeholder_shortcut(request, width):
    return redirect(reverse('placeholder:placeholder', args=[width, width]))

placeholder/templates/placeholder/home.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <title>ImgQuik - because I ran out of ideas.</title>
    <link href="//cdn.muicss.com/mui-0.9.30/css/mui.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css"/>
</head>

<body>
    <div id="content-wrapper" class="mui--text-center">
        <h1>ImqQuik</h1>
        <p>This server can be used for serving placeholder images for any web page.</p>
        <p>To request a placeholder image of a given width and height simply include an image
            with the source pointing to <b>/image/&lt;width&gt;x&lt;height&gt;/</b>
            on this server such as:</p>

        <pre>&lt;img src="{{ example }}" &gt;</pre>

        <h2>Examples</h2>
        <ul id="example-ul">
            <li><img src="{% url 'placeholder:placeholder_bg' width=50 height=50 bg='ccc' %}"></li>
            <li><img src="{% url 'placeholder:placeholder_bg' width=100 height=50 bg='ccc' %}"></li>
            <li><img src="{% url 'placeholder:placeholder_bg' width=50 height=100 bg='ccc' %}"></li>
        </ul>
    </div>
</body>
</html>

templates/base_template.html
<!DOCTYPE html>
{% load "static" %}
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
		<title>{% block title %}{% endblock %}</title>

		<!-- Bootstrap -->
		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
		<link href="{% static 'css/select2.min.css' %}" rel="stylesheet">

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>
		{% block body %}
		<h1>Hello, world!</h1>
		{% endblock %}

		<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
		<script src="{% static 'js/jquery.min.js' %}"></script>
		<!-- Include all compiled plugins (below), or include individual files as needed -->
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
		<script src="{% static 'js/select2.min.js' %}"></script>
	</body>
</html>